global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-aws-vpc
  regions:
    - ap-northeast-1
    - eu-central-1
    - eu-west-1
    - us-east-1
  reporting: true
tests:
  public:
    parameter_input: aws-vpc-public.json
    template_file: aws-vpc.template
