global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-aws-vpc
  regions:
    - eu-west-1
  reporting: true
tests:
  defaults:
    parameter_input: aws-vpc-defaults.json
    template_file: aws-vpc.template
